name: flutter_app
description: "แอป Flutter 101 สำหรับฝึกเรียน"
publish_to: 'none' # กันไม่ให้เผลอ publish ขึ้น pub.dev

version: 1.0.0+1 # รูปแบบ: <version>+<build number>

environment:
  sdk: ^3.12.2

# แพ็กเกจที่แอปต้องใช้ตอนรันจริง
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

# แพ็กเกจที่ใช้เฉพาะตอนพัฒนา/เทสต์ (ไม่รวมในแอปจริง)
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # เพิ่มไฟล์ asset (รูป/ฟอนต์/.env) ที่นี่ เช่น:
  # assets:
  #   - assets/images/logo.png
